### PR TITLE
Pin rack to 1.x

### PR DESCRIPTION
**Pull request by lzap**
Not able to run tests without this.

### CODE REVIEW

**Comment by lzap** [comment]
Can you take a look @iNecas or @domcleal ?

I plan to make new release after tests are green again.

**Comment by domcleal** [comment]
I don't know this project's test suite, and also don't see any test results via the build status on the branches to suggest whether it's correct or not.

**Comment by lzap** [comment]
> I don't know this project's test suite, and also don't see any test results via the build status on the branches to suggest whether it's correct or not.

I run it in beaker:

https://github.com/theforeman/foreman-bats/blob/master/fb-install-ovirt.bats

-- 
Later,
 Lukas #lzap Zapletal

**Comment by iNecas** [comment]
Makes sense to me

**Pull request merged**
