### PR TITLE
Fix: Do not crash when display or cluster info is missing.

### PR DESCRIPTION
**Pull request by davidkupka**
This was crashing on parsing Blank template which had neither display nor cluster tag.

### CODE REVIEW

**Comment by ares** [comment]
:+1:

**Comment by lzap** [comment]
@ares what exactly does work for you? I tested the patch with Foreman develop branch and this bug http://projects.theforeman.org/issues/14090 and it does not fix the problem for me. The same parsing bug is in other places, in my case it fails at /lib/ovirt/vm.rb:240

I suggest to fix all the places here:

```
$ ack .first.text | grep -v rescue
lib/client/vm_api.rb:96:      http_response.xpath("/disk/active").first.text.upcase == "TRUE"
lib/client/vm_api.rb:119:      return (xml_response/'action/status').first.text.strip.upcase=="COMPLETE"
lib/client/vm_api.rb:125:      return (xml_response/'action/status').first.text.strip.upcase=="COMPLETE"
lib/client/vm_api.rb:135:      (xml_response/'action/ticket/value').first.text
lib/ovirt/cluster.rb:6:      super(client, xml[:id], xml[:href], (xml/'name').first.text)
lib/ovirt/host.rb:6:      super(client, xml[:id], xml[:href], (xml/'name').first.text)
lib/ovirt/host.rb:16:      @status = (xml/'status').first.text
lib/ovirt/datacenter.rb:7:      super(client, xml[:id], xml[:href], (xml/'name').first.text)
lib/ovirt/datacenter.rb:16:      @status = (xml/'status').first.text.strip
lib/ovirt/template.rb.orig:6:      super(client, xml[:id], xml[:href], (xml/'name').first.text)
lib/ovirt/template.rb.orig:35:      @memory = (xml/'memory').first.text
lib/ovirt/template.rb.orig:36:      @profile = (xml/'type').first.text
lib/ovirt/volume.rb:7:      super(client, xml[:id], xml[:href], (xml/'name').first.text)
lib/ovirt/volume.rb:51:     @size = (xml/'size').first.text
lib/ovirt/volume.rb:53:     @bootable = (xml/'bootable').first.text
lib/ovirt/volume.rb:54:     @interface = (xml/'interface').first.text
lib/ovirt/vm.rb:12:      super(client, xml[:id], xml[:href], (xml/'name').first.text)
lib/ovirt/vm.rb:234:      @memory = (xml/'memory').first.text
lib/ovirt/vm.rb:235:      @profile = (xml/'type').first.text
lib/ovirt/vm.rb:240:        :type => (xml/'display/type').first.text,
lib/ovirt/vm.rb:245:        :monitors => (xml/'display/monitors').first.text
lib/ovirt/network.rb:6:      super(client, xml[:id], xml[:href], (xml/'name').first.text)
lib/ovirt/quota.rb:6:      super(client, xml[:id], xml[:href], (xml/'name').first.text)
lib/ovirt/interface.rb:15:        super(client, xml[:id], xml[:href], (xml/'name').first.text)
lib/ovirt/interface.rb:44:     @interface = (xml/'interface').first.text
lib/ovirt/interface.rb:46:     @plugged = (xml/'plugged').first.text if (xml/'plugged').first
lib/ovirt/interface.rb:47:     @linked = (xml/'linked').first.text if (xml/'linked').first
lib/ovirt/template.rb:6:      super(client, xml[:id], xml[:href], (xml/'name').first.text)
lib/ovirt/template.rb:35:      @memory = (xml/'memory').first.text
lib/ovirt/template.rb:36:      @profile = (xml/'type').first.text
lib/ovirt/template.rb:39:        :type => (xml/'display/type').first.text,
lib/ovirt/template.rb:40:        :monitors => (xml/'display/monitors').first.text
lib/ovirt/template_version.rb:10:      @version_number = (xml/"version_number").first.text
lib/ovirt/template_version.rb:11:      @version_name = (xml/"version_name").first.text
lib/ovirt/storage_domain.rb:6:      super(client, xml[:id], xml[:href], (xml/'name').first.text)
lib/ovirt/storage_domain.rb:16:      @role = (xml/'type').first.text
lib/ovirt/storage_domain.rb:17:      @kind = (xml/'storage/type').first.text
lib/ovirt/affinity_group.rb:7:      super(client, xml[:id], xml[:href], (xml/'name').first.text)
lib/ovirt/affinity_group.rb:30:     @name = (xml/'name').first.text
lib/ovirt/affinity_group.rb:31:     @positive = (xml/'positive').first.text if (xml/'positive')
lib/ovirt/affinity_group.rb:32:     @enforcing = (xml/'enforcing').first.text if (xml/'enforcing')
```

Keep in mind that if we want this to fix Foreman, we need to backport this into 0.0.3x series as the 0.1 version is not compatible with Fog/Foreman.

**Comment by ares** [comment]
@lzap it fixes this bug http://projects.theforeman.org/issues/11079 for me, some templates are missing display and cluster info...

I don't say it fixes all attributes and I'm sure you can improve other places as well but that shouldn't block this PR.

**Comment by lzap** [comment]
Well, this PR is a chance to fix all of them. I will create a new one that fixes my bug, your bug and broken tests (https://github.com/abenari/rbovirt/issues/100)

**Comment by lzap** [comment]
Ok this looks like it:

```diff
diff --git a/lib/ovirt/template.rb b/lib/ovirt/template.rb
index fba0ad0..10b4b1b 100644
--- a/lib/ovirt/template.rb
+++ b/lib/ovirt/template.rb
@@ -39,8 +39,8 @@ module OVIRT
       @profile = (xml/'type').first.text
       @cluster = Link::new(@client, (xml/'cluster').first[:id], (xml/'cluster').first[:href])
       @display = {
-        :type => (xml/'display/type').first.text,
-        :monitors => (xml/'display/monitors').first.text
+        :type => (xml/'display/type').first.text rescue '',
+        :monitors => (xml/'display/monitors').first.text rescue 0
       }
       @cores = ((xml/'cpu/topology').first[:cores].to_i * (xml/'cpu/topology').first[:sockets].to_i rescue nil)
       @storage = ((xml/'disks/disk/size').first.text rescue nil)
diff --git a/lib/ovirt/vm.rb b/lib/ovirt/vm.rb
index 19eed0c..b4bf74d 100644
--- a/lib/ovirt/vm.rb
+++ b/lib/ovirt/vm.rb
@@ -306,12 +306,12 @@ module OVIRT
       @host = Link::new(@client, (xml/'host').first[:id], (xml/'host').first[:href]) rescue nil
       @cluster = Link::new(@client, (xml/'cluster').first[:id], (xml/'cluster').first[:href])
       @display = {
-        :type => (xml/'display/type').first.text,
+        :type => (xml/'display/type').first.text rescue '',
         :address => ((xml/'display/address').first.text rescue nil),
         :port => ((xml/'display/port').first.text rescue nil),
         :secure_port => ((xml/'display/secure_port').first.text rescue nil),
         :subject => ((xml/'display/certificate/subject').first.text rescue nil),
-        :monitors => (xml/'display/monitors').first.text
+        :monitors => (xml/'display/monitors').first.text rescue 0
       }
       @cores = ((xml/'cpu/topology').first[:cores].to_i * (xml/'cpu/topology').first[:sockets].to_i rescue nil)
       @storage = ((xml/'disks/disk/size').first.text rescue nil)
```

@davidkupka can you amend the additional hung into your patch please ^ ?

**Comment by sandersr** [comment]
Fixes my problem!

**Comment by lzap** [comment]
Cool! I am closing this tho, will create new PR based on my improved patch. :-) Testing is welcome!

**Pull request closed without merging**
