### PR TITLE
Implement VM creation on a specified storage domain (fixed)

### PR DESCRIPTION
**Pull request by pdilung**
Sometimes it might be useful to specify which storage domain should be used when creating a new VM by `OVIRT::Client#create_vm`.
This patch makes it possible to create a VM on a specific storage domain by passing `:storage_domain => '<storage_domain_id>` in VM creation `opts`.
The good thing is that the VM is created even if the _"root volume"_ of a given template is located on a different storage domain.
The _"root_volume:_ is determined as the first volume of template's list of volumes.

@abenari, @jhernand Could we have this merged?

### CODE REVIEW

**Comment by jhernand** [comment]
It isn't conceptually correct to assume that a VM is created in one storage domain. Actually a VM may be created with several disks, and each of those disks can be stored in a different storage domain. To support this correctly it could be better to add to the `create_vm` method a parameter that contains a list of `Volume` objects, each specifying the disk identifier (taken from the template) and the identifier of the storage domain where it is going to be created.

**Comment by pdilung** [comment]
@jhernand I agree that a VM may contain several disks and any of these disks may be located on a different storage_domain. The aim of this PR is to provide a way how to define a storage domain for a _root_ volume during creation of VM from a template.

**Comment by pdilung** [comment]
@jhernand Would you consider to merge?

**Comment by jhernand** [comment]
I think it can't be merged, as the volume that is selected is random, there is no guarantee that the first (or last) disk is the `root` disk. Consider adding a parameter that contains a list of `Volume` objects, those can then contain the target storage domain identifier. You can then achieve your objective creating one new `Volume` object for each disk in the template, and assigning to all of them the same storage domain identifier.

**Comment by pdilung** [comment]
@jhernand OK, I see. I'll try to rethink the whole thing and re-implement it. I propose then to close this PR, open an issue with a feature request where I describe the problem more in detail and then create a (hopefully) final PR. Does that sound like a plan?

**Comment by jhernand** [comment]
Yes, makes sense.

**Comment by pdilung** [comment]
Closing as wontfix in favor of #89

**Pull request closed without merging**
