### PR TITLE
Removed RestClient patch since the newer versions support it already.

### PR DESCRIPTION
**Pull request by Fryguy**
I noticed that rest-client 1.7.0 supported the patch in question, and they are already up to 1.7.2.  I changed the gemspec to have 1.7.0 as the minimum version since rbovirt requires the ca store param.

All of the specs passed, however I'm not sure the specs cover the ca store requirement.

### CODE REVIEW

**Comment by bazulay** [comment]
@abenari  @domcleal  ping

**Comment by domcleal** [comment]
@bazulay I don't have anything to do with maintenance of this gem, so it's not really up to me... my only interest is knowing if/when it breaks Foreman :)

**Comment by abenari** [comment]
@jhernand I don't have objections nor a way to test the changes, go a head and merge.
Since this change breaks compatibility, please change the gem version number from 0.0.x to 0.1.x.

**Comment by Fryguy** [comment]
Updated the PR because of the merge conflict.

I honestly lost track of the prior conversation :smile: I see PR #55 was closed, so I'm in sort of a limbo on what to do.  So, I'll leave it up to you guys to see if you want to merge.

I see that another monkey-patch came in since I first put in this PR, which is kind of unfortunate, but at least it just looks like an added method.

**Comment by pdilung** [comment]
@Fryguy the monkey patch only adds a DELETE method that accepts a body and sends it to the endpoint. I am not happy having it there but this one is needed in order to be able to detach a volume from a VM (details can be found in #60) . Any better idea is appreciated :)

**Comment by abenari** [comment]
@Fryguy a code that test for rest-client version and include the patch only if it's needed could be a good idea.
I understand that Foreman currently depends on rails 1.8 and are locked to older rest-client. I wouldn't like to break compatibility for them.
As for #55 its in preparation for replacing open-ssl with curb, I hope that work will be done in the future.

**Comment by abenari** [comment]
Thanks, @Fryguy merged with version bump and gem spec requiring 1.9.3 as minimal ruby version.

**Comment by kbrock** [comment]
@abenari Thanks for getting this in.

**Comment by pdilung** [comment]
@abenari thanks for getting this in as well.

**Pull request merged**
