### PR TITLE
Add instance types support.

### PR DESCRIPTION
**Pull request by bagasse**
Add read only support of instance types. oVirt added support of instance types in version 3.5. Tested against oVirt 3.5 and 3.6.

### CODE REVIEW

**Comment by lzap** [comment]
Hey thanks, do you have Foreman-related tickets for this one?

**Comment by bagasse** [comment]
@domcleal point me to #5441 when i posted this RFE on the ML. I will post an PR on the fog part when this one will be ok.

**Comment by lzap** [comment]
Can you add an integration test for that? I assume there are some intance types predefined for new installations, if not, consider extend this to full CRUD.

**Comment by bagasse** [comment]
As described here [1], support of this was added to oVirt 3.5 and it come with predefined instance types based on Openstack ones. I added some very basic tests (get all, get one).

[1] https://www.ovirt.org/develop/release-management/features/virt/instance-types/

**Comment by lzap** [comment]
Merged as d25096226ae571396accbc5f5b3eec4f5f979d28, thank you!

**Comment by lzap** [comment]
For the record, this was backported into `0.0.x` series. Thanks.

**Pull request closed without merging**
