### PR TITLE
adding version to the template class

### PR DESCRIPTION
**Pull request by unorthodoxgeek**
ovirt templates have versions, we want that information available.

### CODE REVIEW

**Comment by jhernand** [comment]
The version of a template is not a simple string, but a structure with three components (see the XML schema from the oVirt Engine repository in [1]):

    <xs:complexType name="TemplateVersion">
      <xs:sequence>
         <xs:element name="base_template" type="Template"  minOccurs="0" maxOccurs="1"/>
         <xs:element name="version_number" type="xs:int"  minOccurs="0" maxOccurs="1" />
         <xs:element name="version_name" type="xs:string"  minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
    </xs:complexType>

With your current code you are getting just the text of the "version" element. That will result in concatenation of the contents of "base_template", "version_number" and "version_name". If only one of them happens to be populated things will work, but the moment two or more are populated your code will get incorrect results.

To do this correctly you need to define a new `TemplateVersion` class corresponding to the above XML complex type, and parse it correctly (maybe only the elements that you currently need). Then the `@version` attribute of the `Template` class should be  an instance of that class.

[1] http://gerrit.ovirt.org/gitweb?p=ovirt-engine.git;a=blob;f=backend/manager/modules/restapi/interface/definition/src/main/resources/modules/restapi/interface/definition/src/main/resources/api.xsd;h=85d76fd3829b8f47265f9211fed5c5de2da9ed2f;hb=HEAD#l493

**Comment by unorthodoxgeek** [comment]
@jhernand - done, pushed a new commit with the TemplateVersion class.

**Comment by jhernand** [comment]
Looks good, thanks.

**Comment by unorthodoxgeek** [comment]
please LMK when this is released in a new version of the gem

**Comment by jhernand** [comment]
Your change is included in release 0.0.32: https://rubygems.org/gems/rbovirt/versions/0.0.32

**Comment by abonas** [comment]
I am not familiar with the specific use case that you are handling, but worth to note that there's an additional new boolean property for stateless vms: use_latest_template_version, I didn't see it was handled in this patch.
see here:
http://www.ovirt.org/Features/Template_Versions#REST_API

**Pull request merged**
