### PR TITLE
Support operating systems

### PR DESCRIPTION
**Pull request by iNecas**
The client now allow to call `operating_systems` to return all available
operating systems. The name then can be passed os value for
`os_type` of vm. Also, I've added support for passing os params that are
compatible with the form we get from vm details:

    :os => { :type => 'rhel_7x86',
            :boot => ['network','hd'],
            :kernel => '..',
            :initrd => '..',
            :cmdline => '.. }

The main reason is to make this option configurable even when going over fog
(that has the :os attribute defined, but not the `:os_type` and others.

### CODE REVIEW

**Comment by iNecas** [comment]
Relates to this bug https://bugzilla.redhat.com/show_bug.cgi?id=1315281

**Comment by lzap** [comment]
I assume it replaces https://github.com/abenari/rbovirt/pull/99, can you confirm please?

**Comment by iNecas** [comment]
@lzap no, I have not touch that logic here, as I was not able to reproduce the described issue in #99 yet

**Comment by lzap** [comment]
Can you add simple integration test? Just list OSes and check for one of these. To know that the API works.

**Comment by lzap** [comment]
Merged bunch of PRs, please resolve conflicts and I will start testing.

**Comment by lzap** [comment]
Merged as eb23f225b6bf1c71671be77289fe18c30fc7c04a, thank you!

**Pull request closed without merging**
