### PR TITLE
New release 0.1.0 information

### PR DESCRIPTION
**Pull request by karmab**

### CODE REVIEW

**Comment by karmab** [comment]
@pdilung do you happen to know the details ?

**Comment by pdilung** [comment]
@karmab Let me research

**Comment by pdilung** [comment]
@karmab try to check #73

**Comment by karmab** [comment]
ok, didnt realize that. updated the PR accordingly

**Comment by jhernand** [comment]
I did some formatting changes to your commit and merged it, so I'm closing this pull request. Thanks.

**Pull request closed without merging**
